### PR TITLE
Add travis config for testing against multiple ruby versions

### PR DESCRIPTION
**Pull request by PikachuEXE**
Also add missing dependencies

### CODE REVIEW

**Comment by PikachuEXE** [comment]
[The build is green](https://travis-ci.org/PikachuEXE/ruby-refrigerator/builds/213286741)

**Comment by jeremyevans** [comment]
Thanks for the patch!  I added another patch that modifies the travis configuration to be more like my other projects, and starts testing on JRuby, but it is good to add CI at this point.

**Comment by PikachuEXE** [comment]
I was trying to change `eval` to something else but failed
Got many things that cannot be fetched by `module_eval` 
(`ARGF.class`, `Complex::compatible`)

Also some constants are undefined until file required (like `Date`)

**Comment by jeremyevans** [comment]
The things that cannot be fetched by `eval` issue could be handled by removing constant names from the `module_names/*.txt` file.  Those files were produced by something like: `ruby -e 'ObjectSpace.each_object(Module){|e| p e}'`.  The code already uses `defined?` to check if the constants actually exist.

In terms of the `Date` issue, it's only handled on ruby 2.0 and 2.1, and that's because it is available by default in those versions.  I guess I could have used `--disable-gems` (it's defined by rubygems in those versions), but then it doesn't really reflect what ruby loads by default.

Anyway, I don't think this is a bug, though it could certainly be implemented differently.

**Comment by PikachuEXE** [comment]
Might worth mentioning how those lists of constants are obtained in README (`ruby -e 'ObjectSpace.each_object(Module){|e| p e}'`)

**Comment by jeremyevans** [comment]
Good idea, I've pushed a README update, as well as a Rakefile task that can generate the files for new ruby versions.

**Comment by PikachuEXE** [comment]
Great :)

**Pull request merged**
